"""
Argus Auto Review - GitHub Actions Integration
Automatically review code changes and post comments on PRs
"""
import os
import sys
import json
import requests
from typing import List, Dict


class ArgusAutoReviewer:
    """Automated code reviewer for GitHub Actions."""
    
    def __init__(self, api_url: str = "http://localhost:8000"):
        self.api_url = api_url
        self.github_token = os.getenv("GITHUB_TOKEN")
        self.repo = os.getenv("GITHUB_REPOSITORY", "")
        self.pr_number = os.getenv("PR_NUMBER", "")
        
    def get_changed_files(self) -> List[Dict]:
        """Get list of changed files in the PR."""
        # This would be called from GitHub Actions with proper context
        # For now, return mock data
        print("📋 Getting changed files...")
        
        # In real scenario, use GitHub API
        # url = f"https://api.github.com/repos/{self.repo}/pulls/{self.pr_number}/files"
        # headers = {"Authorization": f"token {self.github_token}"}
        # response = requests.get(url, headers=headers)
        
        # Mock data for testing
        changed_files = [
            {
                "filename": "drivers/usb/core/hub.c",
                "patch": """@@ -123,6 +123,7 @@ static int hub_probe(struct usb_interface *intf,
     struct usb_hub *hub;
     struct usb_device *hdev;
     int ret;
+    int uninitialized_var;
 
     hdev = interface_to_usbdev(intf);
     hub = kzalloc(sizeof(*hub), GFP_KERNEL);"""
            }
        ]
        
        print(f"✅ Found {len(changed_files)} changed file(s)")
        return changed_files
    
    def review_file(self, filename: str, patch: str) -> Dict:
        """Submit a file patch for AI review."""
        print(f"\n🔍 Reviewing: {filename}")
        
        try:
            response = requests.post(
                f"{self.api_url}/api/v1/review",
                json={
                    "patch": patch,
                    "project_name": self.repo.split("/")[-1] if self.repo else "unknown",
                    "file_path": filename
                },
                timeout=120
            )
            
            if response.status_code == 200:
                result = response.json()
                print(f"✅ Review completed for {filename}")
                return result
            else:
                print(f"❌ API error: {response.status_code}")
                return {"success": False, "error": response.text}
                
        except Exception as e:
            print(f"❌ Review failed: {e}")
            return {"success": False, "error": str(e)}
    
    def format_comment(self, filename: str, review_result: Dict) -> str:
        """Format AI review result into GitHub comment."""
        
        if not review_result.get("success"):
            return f"❌ **Review Failed**\n\nError: {review_result.get('error', 'Unknown')}"
        
        issues = review_result.get("issues", [])
        
        if not issues:
            return f"✅ **AI Review Passed**\n\nNo issues found in `{filename}`"
        
        comment = f"## 🤖 AI Code Review - `{filename}`\n\n"
        comment += f"**Summary:** {review_result.get('summary', 'Review completed')}\n\n"
        comment += "---\n\n"
        
        for i, issue in enumerate(issues, 1):
            severity = issue.get("severity", "Info")
            
            # Add emoji based on severity
            if severity == "Critical":
                emoji = "🔴"
            elif severity == "Warning":
                emoji = "🟡"
            else:
                emoji = "🔵"
            
            comment += f"### {emoji} Issue #{i}: {severity}\n\n"
            comment += f"**Problem:**\n{issue.get('issue', 'N/A')}\n\n"
            comment += f"**Suggestion:**\n{issue.get('suggestion', 'N/A')}\n\n"
            comment += "---\n\n"
        
        comment += "\n*Generated by Argus AI Code Reviewer*"
        
        return comment
    
    def post_pr_comment(self, comment: str):
        """Post comment to GitHub PR."""
        if not self.github_token or not self.pr_number:
            print("⚠️  Skipping PR comment (no GitHub context)")
            print(f"Comment would be:\n{comment}")
            return
        
        print(f"\n💬 Posting comment to PR #{self.pr_number}...")
        
        url = f"https://api.github.com/repos/{self.repo}/issues/{self.pr_number}/comments"
        headers = {
            "Authorization": f"token {self.github_token}",
            "Accept": "application/vnd.github.v3+json"
        }
        data = {"body": comment}
        
        try:
            response = requests.post(url, json=data, headers=headers)
            
            if response.status_code == 201:
                print("✅ Comment posted successfully!")
            else:
                print(f"❌ Failed to post comment: {response.status_code}")
                print(response.text)
                
        except Exception as e:
            print(f"❌ Error posting comment: {e}")
    
    def run(self):
        """Main execution flow."""
        print("="*60)
        print("🚀 Argus Auto Review - GitHub Actions")
        print("="*60)
        
        # Step 1: Get changed files
        changed_files = self.get_changed_files()
        
        if not changed_files:
            print("ℹ️  No files to review")
            return
        
        # Step 2: Review each file
        all_comments = []
        for file_info in changed_files:
            filename = file_info["filename"]
            patch = file_info["patch"]
            
            # Submit for review
            review_result = self.review_file(filename, patch)
            
            # Format comment
            comment = self.format_comment(filename, review_result)
            all_comments.append(comment)
        
        # Step 3: Post combined comment
        if all_comments:
            combined_comment = "\n\n".join(all_comments)
            self.post_pr_comment(combined_comment)
        
        print("\n" + "="*60)
        print("✅ Auto review completed!")
        print("="*60)


def main():
    """Entry point for GitHub Actions."""
    
    # Get API URL from environment or use default
    api_url = os.getenv("ARGUS_API_URL", "http://localhost:8000")
    
    # Create reviewer instance
    reviewer = ArgusAutoReviewer(api_url=api_url)
    
    # Run auto review
    reviewer.run()


if __name__ == "__main__":
    main()
