"""
Ultra-simple demo: GitHub Actions + Argus API = Auto PR Comments
This script simulates the entire workflow in one command.
"""
import os
import sys
import json
import requests
from datetime import datetime


def demo_auto_review():
    """
    Simulate the complete auto-review workflow:
    1. Detect code changes (mock)
    2. Call Argus API for review
    3. Generate GitHub comment
    4. Display result
    """
    
    print("="*70)
    print("🤖 Argus Auto Review - DEMO MODE")
    print("="*70)
    print()
    
    # Step 1: Mock code change detection
    print("📍 Step 1: Detecting code changes...")
    changed_files = [
        {
            "filename": "drivers/usb/core/hub.c",
            "patch": """@@ -123,6 +123,7 @@ static int hub_probe(struct usb_interface *intf,
     struct usb_hub *hub;
     struct usb_device *hdev;
     int ret;
+    int uninitialized_var;
 
     hdev = interface_to_usbdev(intf);
     hub = kzalloc(sizeof(*hub), GFP_KERNEL);"""
        }
    ]
    print(f"   ✅ Found {len(changed_files)} changed file(s)")
    print()
    
    # Step 2: Call Argus API
    print("🔍 Step 2: Calling Argus API for AI review...")
    api_url = os.getenv("ARGUS_API_URL", "http://localhost:8000")
    
    try:
        response = requests.post(
            f"{api_url}/api/v1/review",
            json={
                "patch": changed_files[0]["patch"],
                "project_name": "linux-kernel",
                "file_path": changed_files[0]["filename"]
            },
            timeout=120
        )
        
        if response.status_code == 200:
            review_result = response.json()
            print(f"   ✅ Review completed successfully")
        else:
            print(f"   ⚠️  API returned {response.status_code}, using mock result")
            review_result = {
                "success": True,
                "issues": [
                    {
                        "issue": "The variable `uninitialized_var` is declared but not used.",
                        "severity": "Warning",
                        "suggestion": "Remove the unused variable `uninitialized_var`."
                    }
                ],
                "summary": "Found 1 issue(s)"
            }
            
    except Exception as e:
        print(f"   ⚠️  API connection failed: {e}")
        print(f"   Using mock review result for demonstration")
        review_result = {
            "success": True,
            "issues": [
                {
                    "issue": "The variable `uninitialized_var` is declared but not used.",
                    "severity": "Warning",
                    "suggestion": "Remove the unused variable `uninitialized_var`."
                }
            ],
            "summary": "Found 1 issue(s)"
        }
    
    print()
    
    # Step 3: Format GitHub comment
    print("💬 Step 3: Formatting GitHub PR comment...")
    
    issues = review_result.get("issues", [])
    
    comment = f"## 🤖 AI Code Review - `{changed_files[0]['filename']}`\n\n"
    comment += f"**Summary:** {review_result.get('summary', 'Review completed')}\n\n"
    comment += "---\n\n"
    
    for i, issue in enumerate(issues, 1):
        severity = issue.get("severity", "Info")
        
        # Add emoji based on severity
        if severity == "Critical":
            emoji = "🔴"
        elif severity == "Warning":
            emoji = "🟡"
        else:
            emoji = "🔵"
        
        comment += f"### {emoji} Issue #{i}: {severity}\n\n"
        comment += f"**Problem:**\n{issue.get('issue', 'N/A')}\n\n"
        comment += f"**Suggestion:**\n{issue.get('suggestion', 'N/A')}\n\n"
        comment += "---\n\n"
    
    comment += "\n*Generated by Argus AI Code Reviewer*"
    
    print(f"   ✅ Comment formatted ({len(comment)} chars)")
    print()
    
    # Step 4: Display result
    print("="*70)
    print("📝 GENERATED GITHUB COMMENT:")
    print("="*70)
    print()
    print(comment)
    print()
    print("="*70)
    print("✅ DEMO COMPLETED SUCCESSFULLY!")
    print("="*70)
    print()
    print("🎯 What just happened:")
    print("   1. GitHub Actions detected code changes")
    print("   2. Called Argus API with the patch")
    print("   3. AI analyzed the code and found issues")
    print("   4. Generated a structured PR comment")
    print()
    print("🚀 In production, this comment would be automatically posted to the PR!")
    print()


if __name__ == "__main__":
    demo_auto_review()
